---
- hosts: gerlaptops
  sudo: yes
  tasks:
    - name: jdk
      apt: name=openjdk-8-jdk install_recommends=yes state=present

    - name: common packages
      apt: pkg={{ item }} state=present
      with_items:
      - postgresql-9.4
      - ruby
      - ruby-dev
      - javascript-common
      
    - name: elasticsearch
      apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
    - apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main' state=present
    - apt: name=elasticsearch state=present

    - name: nodejs
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - apt_repository: repo='deb https://deb.nodesource.com/node_5.x wily main' state=present filename='nodesource'
    - apt_repository: repo='deb-src https://deb.nodesource.com/node_5.x wily main' state=present filename='nodesource'
    - apt: name=nodejs state=present

    - name: mongodb
      apt_key: keyserver=keyserver.ubuntu.com id=EA312927
    - apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present filename='mongodb-org-3.2'
    - apt: name=mongodb-org state=present

    # TODO fails, probably because of / at the end
    #- name: neo4j
    #  apt_key: url=https://debian.neo4j.org/neotechnology.gpg.key
    #- apt_repository: repo='deb http://debian.neo4j.org/repo stable/' state=present filename='neo4j'
    #- apt: name=neo4j state=present

    - name: ethereum
      apt: name=software-properties-common
    - apt_key: keyserver=keyserver.ubuntu.com id=923F6CA9
    - apt_repository: repo='ppa:ethereum/ethereum'
    - apt: pkg={{ item }} state=present
      with_items:
      - ethereum
      - solc

    - name: insync
      apt_key: url=https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key
    - apt_repository: repo='deb http://apt.insynchq.com/ubuntu wily non-free contrib' state=present
    - apt: name=insync state=present

    # TODO install Google-chome and Dropbox.






