---
- hosts: gerlaptops
  become_method: sudo
  become_user: root
  roles:
   - { role: gerbrands-laptop }

- hosts: gerservers
  roles:
#    - syncthing
    - owncloud
#    - mysql
    - postgresql
#  - ethereum
    - btsync
    - nodejs
