---
- hosts: gerlaptops
  become_method: sudo
  become_user: root
  roles:
   - { role: gerbrands-laptop }

- hosts: gerservers
  roles:
#    - syncthing
    - plutus-ansible-roles/owncloud
#    - mysql
    - plutus-ansible-roles/postgresql
#  - ethereum
    - btsync
    - plutus-ansible-roles/nodejs
