- name: common packages
  sudo: yes
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
  - build-essential
  - ruby
  - ruby-dev
  - python3-dev
  - python-dev
  - javascript-common
  - vlc
  - filezilla
  - git
  - mcedit
  - ubuntu-dev-tools
  - gnu-standards
  - libtool
  - nmap

- name: common packages with recommends
  apt: name={{ item }} install_recommends=yes state=present
  with_items:
  - keepass2
  - virtualbox
  - vagrant
  - calibre
  - thunderbird
