- name: common packages
  sudo: yes
  apt: pkg={{ item }} install_recommends=no state=present
  with_items:
  - ruby
  - ruby-dev
  - python3-dev
  - python-dev
  - javascript-common
  - vlc
  - filezilla
  - git
  - mcedit

- name: common packages with recommends
  apt: name={{ item }} install_recommends=yes state=present
  with_items:
  - keepass2
  - virtualbox
  - vagrant
