- name: btsync
  apt_key: url='https://linux-packages.resilio.com/resilio-sync/key.asc'

- apt_repository: repo='deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free' state=present filename='resilio-sync'

- apt: name=resilio-sync state=present
